---
title: Anuragjain67.Github.Io
timezone: Asia/Kolkata
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
baseurl: "/"
url: http://anuragjain67.github.io
nav:
  main:
    blog: "https://blog.anurag.club"
    medium: "https://jainanurag.medium.com"
  writing:
    all: "/writing"
    popular: "/writing/popular"
    tags: "/writing/tags"
    rss: "/feed.xml"
name: Anurag Jain
slogan: Software Engineer by ❤️.
description: Learn & Share
thumbnail_path: anurag-jain.png
website_repo_url: https://github.com/anuragjain67/anuragjain67.github.io
contact_urls:
  linkedin:
    url: https://www.linkedin.com/in/anuragjain67
    label: LinkedIn
    icon: linkedin-square
  blog:
    url: https://blog.anurag.club
    label: Blog
    icon: pencil-square
  medium:
    url: https://jainanurag.medium.com
    label: Medium
    icon: medium
  github:
    url: https://github.com/anuragjain67/
    label: GitHub
    icon: github-square
paginate: 10
paginate_path: "/writing/page:num"
permalink: "/writing/:year/:month/:day/:title"
sass:
  sass_dir: "/assets/css"
  style: :compressed
highlighter: rouge
gems:
- jekyll-paginate
