# Site settings
author: Anurag Jain
title: New Technologies - Problem and Solution
baseurl: "" # the subpath of your site, e.g. /blog/
twitter_username: theanuragjain
github_username:  anuragjain67

# Build settings
markdown: kramdown
